//
//  StringValues.swift
//  Sibdiet
//
//  Created by amin sadeghian on 7/14/19.
//  Copyright © 2019 maminyoo. All rights reserved.
//

//        dietConnection.getData("0018003104455", "390941")
//        dietConnection.getData("0061123145678", "589185")
//        dietConnection.getData("00447557077488", "519098")
//        dietConnection.getData("00491702322473", "575916")
//        dietConnection.getData("09027153024", "596991")

import UIKit

let deviceId = UIDevice.current.identifierForVendor!.uuidString

var language  : String{ settings.language }
var direction : String{ isFA ? RTL : LTR }

//MARK: Languages
let EN = "EN"
let AR = "AR"
let FA = "FA"
let IR = "IR"
let FA_IR = "fa-IR"
let GB_EN = "gb-EN"

let shareDescription = isRTL ? "رژیم درمانی بر اساس مزاج و متابولیسم بدن" : "Diet Therapy based on Temperament & Metabolism"
let appURL = "https://apps.apple.com/us/app/sibdiet-%D8%B1%DA%98%DB%8C%D9%85-%D8%AF%D8%B1%D9%85%D8%A7%D9%86%DB%8C/id1450280982"

let shareLink =  ["SibDiet iOS App" + "\n" + shareDescription + "\n" + appURL]

//MARK: Strings
let MALE = "MALE"
let Male = "Male"
let FEMALE = "FEMALE"
let Female = "Female"
let SINGLE = "SINGLE"
let MARRIED = "MARRIED"
let Married = "Married"
let MOTAAHEL = "متاهل"
let BABY = "BABY"
let MOANAS = "مونث"
let MOZAKAR = "مذکر"
let ELEMENTARY = "ELEMENTARY"
let ROOZ = "روز"
let MAH = "ماه"
let SAL = "سال"
let CONNECTION_ERROR_EN = "Internet connection error"
let CONNECTION_ERROR_FA = "خطای اتصال به اینترنت"

let MONDAY = "MONDAY"
let TUESDAY = "TUESDAY"
let WEDNESDAY = "WEDNESDAY"
let THURSDAY = "THURSDAY"
let FRIDAY = "FRIDAY"
let SATURDAY = "SATURDAY"
let SUNDAY = "SUNDAY"
let Saturday = "Saturday"
let Sunday = "Sunday"
let Monday = "Monday"
let Tuesday = "Tuesday"
let Wednesday = "Wednesday"
let Thursday = "Thursday"
let Friday = "Friday"

let MON = "Mon"
let TUE = "Tue"
let WED = "Wed"
let THU = "Thu"
let FRI = "Fri"
let SAT = "Sat"
let SUN = "Sun"
let JOME = "جمعه"
let PANSHANBE = "پنجشنبه"
let CHARSHANBE = "چهارشنبه"
let SESHANBE = "سه شنبه"
let DOSHANBE = "دوشنبه"
let YEKSHANBE = "یکشنبه"
let SHANBE = "شنبه"
let NUMBER_CHARS = "1234567890۰۱۲۳۴۵۶۷۸۹٠١٢٣٤٥٦٧٨٩"
let OPTIONAL = "Optional"
let EKHTIARI = "اختیاری"

//MARK: Service
let API_KEY = "api_key"
let P = "p"
let M = "m"
let R = "r"
let D = "d"
let T = "t"
let E = "e"
let X = "x"
let Y = "y"
let PROFILE_NO = "profileNo"
let ERROR_DESCRIPTION = "error_description"
let NOTVALID = "notvalid"
let OK = "ok"
let KO = "ko"
let MOBILE_ERROR = "پرونده ای با این موبایل موجود می باشد."
let DUPLICATE_ERROR = "این پرونده قبلا ثبت شده است."
let FILENO_ERROR = "پرونده ای با این مشخصات موجود نمی باشد."
let APPCODE = "appcode"
let SIBDIET_APPLE = "sibdietapple"
let PLATFORM = "platform"
let IOS = "ios"
let IOS_ALERT = "ios_alert"
let IOS_BADGE = "ios_badge"
let IOS_SOUND = "ios_sound"
let PROFILE_ID = "profile_id"
let TOKEN = "token"
let PUBLISHED = "published"
let NOTUPDATED = "notupdated"
let PAYMENT = "payment"
let _STATUS = "_STATUS"
let _TRANSACTION_ID = "_TRANSACTION_ID"
let REQUEST = "request"
let SPECIAL = "special"
let PLUS = "+"
let PERCENT_2B = "%2B"
let DEVICE_ID = "device_id"
let SITE_ID = "site_id"
let NAME = "name"
let NEGATIVE_ONE = "-1"
let VER_ID = "verId"
let VER = "ver"
let DES = "des"
let NEEDED = "needed"
let JSN = "json"

//MARK: Diet
let DIET = "diet"
let DIETS = "diets"
let FOODS = "foods"
let BREAD = "bread"
let PREPARTION = "preparation"
let COMPOSITIONS = "compositions"
let RICE = "rice"
let BREAKFASTS = "breakfasts"
let LUNCHES = "lunchs"
let DINNERS = "dinners"
let MORNING_SNACK = "morning_snack_id"
let EVENING_SNACK = "evening_snack_id"
let ISTANBUL_RICE = "istanbul_rice"
let BREANS_RICE = "beans_rice"
let LENTIL_RICE = "lentil_rice"
let MACARONI = "macaroni"
let PRESCRIPTIONS = "prescriptions"
let TITLE = "title"
let PRINT_TITLE = "print_title"
let AMOUNT = "amount"
let USAGE = "usage"
let DESCRIPTION = "description"
let HPRESCRIPTIONS = "hprescriptions"
let IDEAL_WEIGHT = "ideal_weight"
let DATE = "date"
let CREATED = "created"
let PERIOD = "period"
let GOALS = "goals"
let BMI = "bmi"
let OBESITY_DEGREE = "obesityDegree"
let DEFAULT_HISTORY = "defaultsHistory"
let FIRST_WEIGHT = "firstWeight"
let FIRST_STATURE = "firstStature"
let BODY_FAT = "bodyFat"
let FAT = "fat"
let STATUS = "status"
let OVER_WEIGHT = "overWeight"
let IMPLEMENTATIONS = "implementations"
let DISEASES = "diseases"
let ERRANDS = "errands"
let ROOM6 = "room6"
let UNIT = "unit"
let UAMOUNT = "uamount"
let DIET_TITLE = "dietTitle"
let SPECIAL_RECOMENDATION = "specialRecommendation"
let ACTIVITY_TITLE = "activityTitle"
let ACTIVITY_AMOUNT = "activityAmount"
let ACTIVITY_DESCRIPTION = "activityDescription"
let SWEETENER_TITLE = "sweetenerTitle"
let SWEETENER_AMOUNT = "sweetenerAmount"
let SWEETENER_DESCRIPTION = "sweetenerDescription"
let FRUIT_TITLE = "fruitTitle"
let FRUIT_AMOUNT = "fruitAmount"
let FRUIT_DESCRIPTION = "fruitDescription"
let DAIRY_TITLE = "dairyTitle"
let DIARY_AMOUNT = "dairyAmount"
let DIARY_DESCRIPTION = "dairyDescription"
let ONE = "1"
let YEK = "۱"
let TWO = "2"
let DO = "۲"
let THREE = "3"
let SE =  "۳"
let FOUR = "4"
let CHAR = "۴"
let FIVE = "5"
let PANJ = "۵"
let SIX = "6"
let SISH = "۶"
let SEVEN = "7"
let HAFT = "۷"

//MARK: Profile
let ID = "id"
let PROFILE = "profile"
let MOBILE = "mobile"
let FILE_NUMBER = "fileNumber"
let F_NAME = "fname"
let L_NAME = "lname"
let EMAIL = "email"
let APPLE_ID = "apple_id"
let LIMOO_ID = "limoo_id"
let CITY = "city"
let MARITAL = "marital"
let HOME_ADDRESS = "homeaddress"
let GENDER = "gender"
let NATURAL_TAMPER = "natural_temper"
let HOME_PHONE = "homephone"
let BIRTHDAY = "birthday"
let TELEGRAM_ID = "telegram_id"
let JOB = "job"
let EDUCATION = "education"
let BLOOD = "blood"
let COUNTRY = "country"

//MARK: Body
let BODY = "body"
let STATURE = "stature"
let Stature = "Stature"
let GHAD = "قد"
let WEIGHT = "weight"
let Weight = "Weight"
let VAZN = "وزن"
let WRIST = "wrist"
let Wrist = "Wrist"
let DOR_MOCH =  "دور مُچ دست"
let ABDOMINAL = "abdominal"
let Abdominal = "Abdominal"
let DOR_SHEKAM = "دور شكم"
let HIP = "hip"
let Hip = "Hip"
let DOR_BASAN = "دور باسن"
let THIGH = "thigh"
let Thigh = "Thigh"
let DOR_RAN =  "دور ران"
let CHEST = "chest"
let Chest = "Chest"
let DOR_SINE = "دور سینه"
let SHOULDERS = "shoulders"
let Shoulders = "Shoulders"
let TOL_SHANE = "طول شانه ها"
let BIRTH_WEIGHT = "birth_weight"
let Birth_weight = "Birth weight"
let VAZN_TAVALOD = "وزن تولد"
let BIRTH_STATURE = "birth_stature"
let Birth_stature = "Birth stature"
let GHAD_TAVALOD = "قد تولد"
let FATHER_STATURE = "father_stature"
let Father_stature = "Father stature"
let GHAD_PEDAR = "قد پدر"
let MOTHER_STATURE = "mother_stature"
let Mother_stature = "Mother stature"
let GHAD_MADAR = "قد مادر"
let CM = "cm"
let SANTIMETR = "سانتیمتر"
let KG = "kg"
let KILOGRAM = "کیلوگرم"
let C = "C"
let MM = "mm"
let GR = "gr"

//MARK: Views
let LOGIN_VIEW = "loginView"
let DIET_VIEW = "dietView"
let DIET_TABLE_VIEW = "calenderView"
let SUPPLEMENT = "supplement"
let PRESCRIPTION = "prescription"
let SibDiet = "SibDiet"

//MARK: Meals
let BREAKFAST = "breakfast"
let MORNING = "morningSnack"
let LUNCH = "lunch"
let EVENING = "eveningSnack"
let DINNER = "dinner"

//MARK: Directions
let RTL = "RTL"
let LTR = "LTR"

//MARK: QuestionerTypes
let RADIO = "radio"
let CHECK = "check"
let RADIO_DES = "radioDes"
let TEXT = "text"

//MARK: Fonts
let Sahel_Bold = "Sahel-Bold"
let Sahel = "Sahel"
let Shabnam = "Shabnam"
let Nahid = "Nahid"
let Gandom = "Gandom"
let Samim = "Samim"
let GillSans = "GillSans"
let GillSans_Italic = "GillSans-Italic"
let JosefinSans = "JosefinSans"
let AvenirNext_Regular = "AvenirNext-Regular"
let Traffic = "XTraffic"
let Palatino_Roman = "Palatino-Roman"
let Roya = "BRoya"
let AppleSDGothicNeo_Regular = "AppleSDGothicNeo-Regular"
let AppleSDGothicNeo_Light = "AppleSDGothicNeo-light"
let AppleSDGothicNeo_Bold = "AppleSDGothicNeo-Bold"
let HelveticaNeue = "HelveticaNeue"
let HelveticaNeue_Medium = "HelveticaNeue-Medium"
let Yekan = "BYekan"
let Actor_Regular = "Actor-Regular"

//MARK: Sounds
let CAF_EXTENSION = "caf"
let MP3_EXTENSION = "mp3"
let DIET_CELL_SOUND = "timeline_scroll_up"
let QUESTION_SOUND = "swoosh"
let ANSWER_SOUND = "bing"
let DIET_TABLE_SOUND = "wink"
let ANSWER_HGH_SOUND = "event_answer"

//MARK: Images
let BACK_IMG = "back"
let SHARE_IMG = "share"
let DR_IMG = "DrRoshandel"
let MAN_IMG = "profileMan"
let WOMAN_IMG = "profileWomen"
let CHILD_IMG = "profileChild"
let ADD_IMG = "add"
let SUPPORT_IMG = "support"
let CALL_IMG = "call"
let QUESTION_IMG = "question"
let ANSWER_IMG = "answer"
let LOGOUT_IMG = "logout"
let CLEAN_IMG = "cleanForm"
let CLOSE_IMG = "closeP"
let PRESCRIPTION01_IMG = "prescriptions01"
let PRESCRIPTION02_IMG = "prescriptions02"
let DIET01_IMG = "dietDay01"
let DIET02_IMG = "dietDay02"
let SUPPLEMENT01_IMG = "supplement01"
let SUPPLEMENT02_IMG = "supplement02"
let FAMILY_IMG = "family"
let RADIO_01_IMG = "radio01"
let RADIO_02_IMG = "radio02"
let CHECK_01_IMG = "check01"
let CHECK_02_IMG = "check02"
let WORLD_IMG = "world"
let BREAKFAST_IMG = "breakfastWatch"
let MORNINGSNACK_IMG = "morningSnackWatch"
let LUNCH_IMG = "lunchWatch"
let EVENINGSNACK_IMG = "eveningSnackWatch"
let DINNER_IMG = "dinnerWatch"
let UP_IMG = "up"
let SPECIAL_IMG = "specialRecommendation"
let ACTIVITY_IMG = "activity"
let DAIRY_IMG = "dairy"
let FRUIT_IMG = "fruit"
let SWEET_IMG = "sweetener"
let CLEAR_02_IMG = "clear02"
let STOP_IMG = "stop"
let PLAY_IMG = "play"

//MARK: QuestionAnswer
let USERS = "users"
let IDS = "ids"
let DATA = "data"
let TOTAL = "total"
let FIRST_PAGE_URL = "first_page_url"
let NEXT_PAGE_URL = "next_page_url"
let LAST_PAGE_URL = "last_page_url"
let QUESTION = "question"
let QUESTION_CREATED_AT = "question_created_at"
let ANSWER = "answer"
let ANSWER_CREATED_AT = "answer_created_at"
let DAR_ENTEZAR = "در انتظار پاسخ"
let PLEASE_WAIT = "Please wait..."
let U_R_L = "url"

//MARK: Settings
let LANGUAGE = "lang"
let ENABLE_NOTIFICATION = "enableNotification"
let NOT_AVALABLE = "NOT_AVALABLE"

//MARK: Special Questions
let FEETSLEEP = "feetsleep"
let Numbness_in_hands_and_feet = "Numbness in hands and feet"
let KHABRAFTEGI_DAST_PA = "خواب رفتگی دست و پا"

let BLOAT = "bloat"
let Bloat = "Bloat"
let NAFKH =   "نفخ"

let DIARRHEA = "diarrhea"
let Diarrhea = "Diarrhea"
let ESHAL = "اسهال"

let APPETITE = "appetite"
let Appetite = "Appetite"
let ESHTEHA = "اشتها"

let PERIODBLEEDING = "periodbleeding"
let Bleeding_during_periods = "Bleeding during periods"
let KHONRIZI_PERIOD = "خونریزی دوره پریود"

let PERIODPAIN = "periodpain"
let Menstrual_period_pain = "Menstrual period pain"
let DARD_PERIOD = "درد دوره پریود"

let PREGNANT = "pregnant"
let Are_you_currently_pregnant = "Are you currently pregnant?"
let BARDARI =  "آیا باردار هستید؟"

let PREGNANT_MONTHS = "pregnant_months"
let How_many_weeks = "How many weeks?"
let HAFTE_CHANDOM = "هفته چندم بارداری؟ (۱ تا ۴۲)"

let CHILDBIRTH = "childbirth"
let Childbirth = "Childbirth"
let ZAYEMAN = "زایمان"

let BREASTFEEDING = "breastfeeding"
let Breastfeeding = "Breastfeeding Now"
let SHIRDEHI =  "در حال حاضر شیردهی"

let DAIRY_SENSITIVITY = "dairy_sensitivity"
let Are_you_allergic_to_dairy = "Are you allergic to dairy?"
let HASASIYAT_SHIRDEHI =   "در شیردهی به لبنیات حساس هستید؟"

let FIBROMA = "fibroma"
let Fibroma_problem = "Fibroma problem"
let MOSHKEL_FIBROM =  "مشکل فیبروم"

let BREAST_CANCER = "breast_cancer"
let Breast_cancer_problem = "Breast cancer problem"
let SARATAN_PESTAN = "مشکل سرطان پستان"

let OVARIAN_CYST = "ovarian_cyst"
let Ovarian_cyst_problem = "Ovarian cyst problem"
let KIST_TOKHMDAN =  "مشکل کیست تخمدان"

let MOUTH = "mouth"
let Taste_of_your_mouth = "Taste of your mouth?"
let TAME_DAHAN = "طعم دهان"

let METATARSUS = "metatarsus"
let Metatarsus = "Metatarsus"
let KAF_PA = "کف پا"

let BLOOD_CONCENTRATION = "blood_concentration"
let BLOOD_CONCENTRATION_AUDIO = "bloodConcentration"
let Blood_concentration_problems = "Blood concentration problems"
let GHELZAT_KHON = "مشکلات غلظت خون HTC - Hematocrit"

let PLATELET = "platelet"
let Platelets_problem = "Platelets problem - PLT"
let MOSHKEL_PLAKET =  "مشکل پلاکت PLT - Platelt"

let HAIRLOSS = "hairloss"
let Hair_problems = "Hair problems"
let MOSHKEL_MO =  "مشکلات مو"

let HAIRLOSS_LOCATION = "hairloss_location"
let Hair_loss_location = "Hair loss location"
let MAHAL_RIZESH_MO =  "محل ریزش مو"

let CONSTIPATION = "constipation"
let Constipation = "Constipation"
let YOBOSAT =  "یبوست"

let SLEEPJUMP = "sleepjump"
let Sleep_jumping = "Sleep jumping"
let PARESH_KHAB = "پرش از خواب"

let ACTIVITY = "activity"
let Physical_activity = "Physical activity"
let FAALIYAT_BADANI =  "فعالیت بدنی"

let ACTIVITY_TYPE = "activity_type"
let Sport_type = "Sport type"
let NOE_VARZESH =  "نوع ورزش"
let Enter_sport = "Enter the name of the sport"
let VARZESH_NAME =  "نام ورزش را وارد نمایید"
let ACTIVITY_OTHER = "activity_other"

let ACTIVITY_DAYS = "activity_days"
let Number_days_week = "Number of days per week"
let TEDAD_ROZ =   "تعداد روزهای ورزش"

let ACTIVITY_TIME = "activity_time"
let Duration_day = "Duration of per day"
let MODAT_VARZESH = "مدت زمان ورزش در هر روز"

let Activity_week_days = "Activity week days"
let ROZHAYE_TAMRIN = "روزهای تمرین در هفته"

let ACTIVITY_WEEK_DAYS = "activity_week_days"
let SAAT_SHORO_TAMRIN = "ساعت شروع تمرین"
let Time_to_start_practicing = "Practice time start"

let ACTIVITI_START_TIME = "activity_start_time"
let SHEDAT_TAMRIN = "شدت تمرین در جلسات مختلف"
let Intensity_of_practice = "Intensity of exercise"
let ACTIVITY_INTENSITY = "activity_intensity"

let TASVIR_BADAN = "تصویر کلی بدن"
let Body_size = "General body image"
let ACTIVITY_ATHLETE_BODY = "activity_athlete_body"

let REJIM_HADAF = "هدف از دریافت رژیم ورزشی"
let Purpose_of_diet = "The purpose of sports nutrition"
let ACTIVITY_DIET_GOAL = "activity_diet_goal"

let VITAMIN_DEFICIENCY_D = "vitamin_deficiency_d"
let Deficiency_D = "Deficiency of vitamin D"
let KAMBOD_VIT_D =  "کمبود ویتامین دی VitD"
let VIT_D_AUDIO = "vitaminDeficiencyD"

let KIDNEY_STONE = "kidney_stone"
let Kidney_stone = "Kidney stone"
let SANG_KOLIYE = "سنگ کلیه"
let kidneyStoneAudio = "kidneyStone"

let MS = "ms"
let MSQ = "MS"
let EM_ES =  "ام اس MS"

let ARTHRITIS = "arthritis"
let Arthritis = "Arthritis"
let ARTOROZ =  "آرتروز"

let ARTHRITIS_DESC = "arthritis_desc"
let Rheumatoid_arthritis = "Rheumatoid arthritis - RA"
let RHEUMATOID_ARTHRITIS = "rheumatoid_arthritis"
let ROMATISM =   "آرتریت روماتوئید (روماتیسم مفصلی)"
let rheumatoidArthritisAudio = "rheumatoidArthritis"

let THINNING_DRUGS = "thinning_drugs"
let Use_drugs = "Use of diluent drugs"
let DARO_RAGHIGH = "استفاده از داروهای رقیق کننده"

let EPILEPSY = "epilepsy"
let Epilepsy = "Epilepsy problem"
let MOSHKEL_SAR =  "مشکل صرع"

let CRAMP = "cramp"
let Cramp = "Cramp"
let GEREFTEGI_AZOLAT =  "گرفتگی عضلات"

let HEADACHE = "headache"
let Headache = "Headache"
let SARDARD =  "سردرد"

let GLUCOSE = "glucose"
let Blood_Glucose = "Blood Glucose"
let GHAND_KHON =   "قند خون FSB - Fasting Blood"

let GALLBLADDER = "gallbladder"
let Gall_bladder = "Gall bladder"
let KISE_SAFRA =  "کیسه‌ صفرا"

let PRESSURE = "pressure"
let Blood_Pressure = "Blood Pressure"
let FESHAR_KHON =  "فشار خون"

let LIVER = "liver"
let Liver_condition = "Liver condition"
let VAZIYAT_KABED =  "وضعیت کبد"

let ANEMIA = "anemia"
let Anemia = "Anemia"
let KAM_KHONI = "کم خونی"

let STOMACH = "stomach"
let Stomach_ache = "Stomach ache"
let DARD_MEDE =  "درد یا سوزش معده"

let STOMACH_INCREASING = "stomach_increasing"
let related_salad_fruit = "Is it related to salad & fruit?"
let ERTEBAT_MIVE_SALAD = "ارتباطی با مصرف سالاد و میوه جات دارد؟"
let STOMACH_INCREASING_DESC = "stomach_increasing_foods"

let MARY = "mary"
let Reflux_heartburn = "Reflux or heartburn"
let REFLUX_MEDE = "ریفلاکس یا همان ترش کردن معده"

//let FAT = "fat"
let Triglycerides_fats = "Triglycerides fats"
let CHARBI_TRIGILISIRID = "چربی تری گلیسیرید TGs - Cholesterol"

let FAT_CHOLESTEROL = "fat_cholesterol"
let fatCholesterolAudio = "fatCholesterol"
let Fat_Cholesterol = "Fat Cholesterol"
let CHARBI_COLESTEROL = "چربی کلسترول Cholesterol"

let THYROID = "thyroid"
let Thyroid_condition = "Thyroid condition"
let TIROEID = "تیروئید"

let URIC = "uric"
let Uric_Acid = "Uric Acid"
let ASID_URIC = "اسید اوریک U.A - Uric Acid"

let BLOOD_UREA = "blood_urea"
let High_blood_urea = "High blood urea"
let URE_KHON =  "اوره بالای خون BUN - Blood Urea"
let BLOOD_UREA_DESC = "blood_urea_desc"

let BLOOD_CREATININE = "blood_creatinine"
let High_blood_creatinine = "High blood creatinine"
let CRATIN_KHON =  "کراتنین بالای خون CR - Creatinine"
let BLOOD_CREATININE_DESC = "blood_creatinine_desc"

let FINGERNAIL = "fingernail"
let How_nails = "How are your nails?"
let VAZIYAT_NAKHON = "وضعیت ناخن های"

let COVID19 = "covid19"
let VAZIAT_CORONA = "وضعیت ابتلا به کرونا"
let Covid_19 = "COVID-19"

let VEGETARIAN = "vegetarian"
let GIAHKHAR = "آیا گیاهخوار هستید؟"
let Are_you_vege = "Are you a vegetarian?"

let HEMORRHOID = "hemorrhoid"
let Hemorrhoids = "Hemorrhoids"
let HEMOROEID = "هموروئید (بواسیر یا همان فیشر)"

let ECONOMIC = "economic"
let EGHTESADI = "آیا تمایل دارید رژیم شما اقتصادی باشد؟"
let Economical = "Do you want your diet to be economical?"

let Breakfast = "Breakfast"
let SOBHANE = "صبحانه"

let Lunch = "Lunch"
let NAHAR =  "ناهار"

let Dinner = "Dinner"
let SHAM = "شام"

let WALKING_STATUS = "walking_status"
let Walk_implementation = "Walk implementation"
let NAHVE_PIYADERAVI =  "نحوه اجرای پیاده روی طبق دستور"

let FOODS_STATUS = "foods_status"
let Implementation_foods = "The implementation of foods"
let NAHVE_GHAZA =  "نحوه اجرای غذاها"

let REFRESHMENTS_STATUS = "refreshments_status"
let During_snacks = "During the regime about snacks"
let NAHVE_TANAGHOLAT =  "در حین رژیم در مورد تنقلات"

let VITAMINS_STATUS = "vitamins_status"
let Vitamins_minerals = "Vitamins and minerals"
let NAHVE_VITAMIN =  "ویتامین و املاح تجویز شده در رژیم"

let WEIGHT_GOAL = "weight_goal"
let What_weight = "What do you want from your weight?"
let KHASTE_VAZN = "از وزنتان چه خواسته ای دارید؟"

let SibDiet_family = "is the SibDiet regime in your family?"
let SIBDIET_FAMILY = "در خانواده فردهِ دیگری رژیم سیب دایت"

let Name = "Name"
let NAM = "نام"
let Name_Family = "Name & Family"
let NAME_MOREDNAZAR =  "نام و نام خانوادگی فرد مورد نظر"

let Mobile = "Mobile"
let SHOMARE_HAMRAH =  "شماره همراه"
let Mobile_number = "Mobile number"
let MOBILE_MOREDENAZAR = "شماره همراه فرد مورد نظر"

let MOKAMEL_SE_MAH = "استفاده از مکمل ها در ۳ ماهه اخیر"
let Using_supplements_3_m = "Supplements in the last 3 months"
let SUPPLEMENT_HISTORY = "activity_supplements_history"

let EXPLANATIONS = "explanations"
let Main_reason = "The main reason for your request *"
let ELAT_DARKHAST =  "علت اصلی درخواست شما *"

let MAIMUM_15_WORD = "Maximum 15 words"
let HADEAKSAR_15_KALAME = "حداکثر ۱۵ کلمه"

let DISEASE = "disease"
let Disease_history = "Disease history"
let BIMARIHAYE_DIGAR =   "بیماری های دیگری که دارید؟"

let FAVORITEFOOD = "favoritefood"
let Favorite_Foods = "Favorite Foods"
let GHAZA_MOREDEALAGHE = "غذاهای مورد علاقه *"
let Maximum_3_items = "Maximum 3 items 'opt'"
let HADEAKSAR_3_MORED =  "حداکثر ۳ مورد (اختیاری)"
let Seporate = "Separate up to 3 item with (,)"
let JODAJODA = "حداکثر ۳ مورد، با ویرگول (،) جدا کنید"

let HATEDFOOD = "hatedfood"
let Hated_Foods = "Hated or Sensitive foods"
let GHAZA_MOREDETANAFOR = "غذای مورد تنفر و یا حساسیت زا"

let SUPP_HOLDER = "Supplements or steroids and derivatives"
let MOKAMLEHA =  "مکمل ها یا استروئیدها و مشتقات"

let ZERO = "0"
let CREATED_ID = "250678"
let CREATED_BY = "created_by"
let SIMILAR_TEXT = "similar_text"
let SIMILAR_MOBILE = "similar_mobile"
let TRACKING_CODE = "tracking_code"
let PAYMENT_DATE = "payment_date"
let PAYMENT_TYPE = "payment_type"

//MARK: Special Answers
let Brief_explanation = "Brief explanation"
let TOZIH_KOTAH = "لطفاً توضیح کوتاهی بدهید"
let NAME_GHAZA = "نام مواد غذایی با مشکلات گوارشی"
let NOT_HAVE = "NOT_HAVE"
let Not_Have = "Not Have"
let NADARAM = "ندارم"
let LOW = "LOW"
let Low = "Low"
let KAM = "کم"
let HIGH = "HIGH"
let High = "High"
let ZIAD = "زیاد"
let NORMAL = "NORMAL"
let Normal = "Normal"
let MAMOLI = "معمولی"
let MENOPAUSE = "MENOPAUSE"
let Menopause = "Menopause"
let YAESTEGI = "یائسگی"
let JNO = "JNO"
let No = "No"
let KHEYR = "خیر"
let JYES = "JYES"
let Yes = "Yes"
let BALE = "بله"
let HAD_NOT = "HAD_NOT"
let Not_Had = "Not Had"
let NADASHTAM = "نداشته ام"
let HAD = "HAD"
let Had = "Had"
let DASHTAM = "داشته ام"
let HAVE = "HAVE"
let Have = "Have"
let DARAM = "دارم"
let HAD_BEFORE = "HAD_BEFORE"
let Had_Before = "Had Before"
let GHABLAN_DASHTAM = "قبلا داشته ام"
let NOT_KNOW = "NOT_KNOW"
let DNT_KNOW = "Dn't know"
let Not_Know = "Not Know"
let Suspicious = "I'm suspicious"
let NEMIDANAM = "نمی دانم"
let MASHKOK = "مشکوک هستم"

let JNONE = "JNONE"
let None = "None"
let HICH = "هیچ"
let BITTER = "BITTER"
let Bitter = "Bitter"
let TALKH = "تلخ"
let SOUR = "SOUR"
let Sour = "Sour"
let TORSH = "ترش"
let SALINE = "SALINE"
let Saline = "Saline"
let SHOR = "شور"
let SWEET = "SWEET"
let Sweet = "Sweet"
let SHIRIN = "شیرین"
let BE_FREEZE = "BE_FREEZE"
let Freeze = "Freeze"
let YAKH = "یخ"
let BE_HOT = "BE_HOT"
let Hot = "Hot"
let DAGH = "داغ"
let BE_DRY = "BE_DRY"
let ADI = "عادی"
let DRY_CRACKED = "Dry & cracked"
let KHOSHK = "خشک و ترک خورده"
let NORMAL_150_400 = "Normal (150 to 400 thousand)"
let MAMOLI_150_400 = "معمولی (۱۵۰ تا ۴۰۰ هزار)"
let DOWN = "DOWN"
let DOWN_150 = "Down (Under 150 thousand)"
let PAEIN_150 = "پایین (زیر ۱۵۰ هزار)"
let UP = "UP"
let UP_400 = "Up (Above 400 thousand)"
let BALA_400 = "بالا (بالای ۴۰۰ هزار)"
let HIGH_LOSS = "HIGH_LOSS"
let High_Loss = "High Loss"
let RIZESH_ZIAD = "ریزش زیاد"
let COINS_LOSS = "COINS_LOSS"
let Coins_Loss = "Coins Loss"
let RIZESH_SEKEI = "ریزش سکه ای"
let DRY_BRITTLE = "DRY_BRITTLE"
let Dry_Brittle = "Dry and Brittle"
let KHOSHK_SHEKANANDE = "خشک و شکننده"
let OILY = "OILY"
let Oily = "Oily"
let CHARB = "چرب"
let TRICHOPTILOSIS = "TRICHOPTILOSIS"
let Has_trichoptilosis = "Has trichoptilosis"
let MOKHORE = "موخوره دارد"
let PREMATURE_GRAYING = "PREMATURE_GRAYING"
let Premature_graying = "Premature graying"
let SEFIDI_ZOODRES = "سفیدی زودرس"
let HICHKODAM = "هیچ کدام"
let FRONT = "FRONT"
let Front_head = "Front of the head"
let AZ_JOLO_SAR = "از جلو سر"
let FLOOR = "FLOOR"
let Floor_head = "Floor of the head"
let AZ_KAF_SAR = "از کف سر"
let FRONT_FLOOR = "FRONT_FLOOR"
let Front_floor = "Front & floor simultaneously"
let AZ_JOLO_KAF = "از جلو و کف سر همزمان"
let ALL_PARTS = "ALL_PARTS"
let all_parts = "From all parts"
let TAMAM_GHESMAT = "از تمام قسمت ها"
let dont_activities = "I don't have any sports activities"
let HICH_VARZESH = "هیچ فعالیت بدنی ندارم"
let Simple_walking = "Simple walking distance"
let PADERAVI = "پیاده روی ساده"
let SOMETIMES = "SOMETIMES"
let Sometimes_recreation = "Sometimes I exercise recreation"
let GAHAN_VARZESH = "گاهاً تفریحی ورزش میکنم"
let PROFESSIONAL = "PROFESSIONAL"
let professional_athlete = "I am a professional athlete"
let VARZESHKAR = "ورزشکار حرفه ای هستم"
let BODYBUILDING = "BODYBUILDING"
let Bodybuilding = "Bodybuilding"
let BADANSAZI = "بدنسازی"
let ZUMBA = "ZUMBA"
let Zumba = "Zumba"
let ZUMBAF = "زومبا"
let TRX = "TRX"
let TRXF = "تی آر ایکس"
let MARTIAL = "MARTIAL"
let Martial = "Martial"
let RAZMI = "رزمی"
let SWIM = "SWIM"
let Swim = "Swim"
let SHENA = "شنا"
let MOUNTAINEERING = "MOUNTAINEERING"
let Mountaineering = "Mountaineering"
let KOHNAVARDI = "کوهنوردی"
let AEROBIC = "AEROBIC"
let Aerboic = "Aerboic"
let AROBIC = "ایروبیک"
let LACE_SPORTS = "LACE_SPORTS"
let Lace_sports = "Lace sports"
let VARZESH_TORI = "ورزش های توری"
let TRACK_AND_FIELD = "TRACK_AND_FIELD"
let Track_Field = "Track and Field"
let DO_MEYDANI = "دو و میدانی"
let SPINNING = "SPINNING"
let Spinning = "Spinning"
let SpinningF = "اسپینینگ"
let GYMNASTICS = "GYMNASTICS"
let Gymnastics = "Gymnastics"
let GIMNASTIC = "ژیمناستیک"
let ROCK_CLIMBING = "ROCK_CLIMBING"
let Rock_climbing = "Rock climbing"
let SAKHRE_NAVARDI = "صخره نوردی"
let BOATING = "BOATING"
let Boating = "Boating"
let GHAYEGHRANI = "قایقرانی"
let SKATE = "SKATE"
let Skate = "Skate"
let SKATEF = "اسکیت"
let SQUASH = "SQUASH"
let Squash = "Squash"
let SKOASH = "اسکوآش"
let BIKE_RIDING = "BIKE_RIDING"
let Bike_riding = "Bike riding"
let DOCHARKHE_SAVARI = "دوچرخه سواری"
let HORSE_RIDING = "HORSE_RIDING"
let Horse_riding = "Horse riding"
let ASB_SAVARI = "اسب سواری"
let CROSSFIT = "CROSSFIT"
let Crossfit = "Crossfit"
let KERASFIT = "کراسفیت"
let PHYSICAL_READINESS = "PHYSICAL_READINESS"
let Physical_readiness = "Physical readiness"
let AMADEGI_JESMANI = "آمادگی جسمانی"
let BADMINTON = "BADMINTON"
let Badminton = "Badminton"
let BADMINTONF = "بدمینتون"
let TENNIS = "TENNIS"
let Tennis = "Tennis"
let TENIS = "تنیس"
let POWERLIFTING = "POWERLIFTING"
let Powerlifting = "Powerlifting"
let POWERLIFTINGF = "پاورلفتینگ"
let BARACELL = "BARACELL"
let Baracell = "Baracell"
let BARACELLF = "باراسل"
let BALLET = "BALLET"
let Ballet = "Ballet"
let BALLE = "باله"
let PILATES = "PILATES"
let Pilates = "Pilates"
let PILATESF = "پیلاتس"
let OTHER_SPORTS = "OTHER_SPORTS"
let Other_Sports = "Other Sports"
let VARZESH_DIGAR = "ورزش های دیگر"
let HALF = "0.5"
let Half_hour = "Half hour"
let NIM_SAAT = "نیم ساعت"
let One_hour = "One hour"
let YEK_SAAT = "یک ساعت"
let ONE_HALF = "1.5"
let One_half = "One & a half hours"
let YEK_NIM = "یک و نیم ساعت"
let Two = "Two hours"
let DO_SAAT = "دو ساعت"
let Three = "Three hours"
let SE_SAAT = "سه ساعت"
let Four = "Four hours"
let CHAR_SAAT = "چهار ساعت"
let HAFT_SOBH = "۷ صبح"
let AM_7 = "07:00 AM"
let HASHT_SOBH = "۸ صبح"
let AM_8 = "08:00 AM"
let EIGHT = "8"
let NOH_SOBH = "۹ صبح"
let AM_9 = "09:00 AM"
let NINE = "9"
let DAH_SOBH = "۱۰ صبح"
let AM_10 = "10:00 AM"
let TEN = "10"
let YAZDAH_SOBH = "۱۱ صبح"
let AM_11 = "11:00 AM"
let ELEVEN = "11"
let DO_ZOHR = "۲ ظهر"
let PM_2 = "02:00 PM"
let FOURTEEN = "14"
let SE_ZOHR = "۳ ظهر"
let PM_3 = "03:00 PM"
let FIFTEEN = "15"
let CHAR_ZOHR = "۴ ظهر"
let PM_4 = "04:00 PM"
let SIXTEEN = "16"
let PANJ_ASR = "۵ عصر"
let PM_5 = "05:00 PM"
let SEVENTEEN = "17"
let SHISH_ASR = "۶ عصر"
let PM_6 = "06:00 PM"
let HASHT_SHAB = "۸ شب"
let EIGHTEEN = "18"
let PM_8 = "08:00 PM"
let NOH_SHAB = "۹ شب"
let TWENTY = "20"
let PM_9 = "09:00 PM"
let TWENTY_ONE = "21"
let DAH_SHAB = "۱۰ شب"
let PM_10 = "10:00 PM"
let TWENTY_TWO = "22"
let CHEHEL_SHAST_DARSAD = "هر ست ۱۲ - ۱۵ تکرار (۴۰٪ ~ ۶۰٪ 1RM)"
let INTENSITY_40_60 = "40-60"
let Intensity_40_60 = "12 - 15 reps/set (40% ~ 60% 1RM)"
let SHAST_HASHTAD_DARSAD = "هر ست ۱۲ - ۶ تکرار (۶۰٪ ~ ۸۰٪ 1RM)"
let INTENSITY_60_80 = "60-80"
let Intensity_60_80 = "6 - 12 reps/set (60% ~ 80% 1RM)"
let HAFTAD_SAD_DARSAD = "هر ست ۵ - ۱ تکرار (۷۰٪ ~ ۱۰۰٪ 1RM)"
let INTENSITY_70_100 = "70-100"
let Intensity_70_100 = "1 - 5 reps/set (70% ~ 100% 1RM)"
let HASHTAD_SAD_DARSAD = "هر ست ۳ - ۱ تکرار (۸۰٪ ~ ۱۰۰٪ 1RM)"
let INTENSITY_80_100 = "80-100"
let Intensity_80_100 = "1 - 3 reps/set (80% ~ 100% 1RM)"
let CHAGH = "چاق"
let Obese = "Obese"
let OBESE = "OBESE"
let LAGHAR = "لاغر"
let Thin = "Thin"
let THIN = "THIN"
let AZOLANI = "عضلانی"
let Muscular = "Muscular"
let MUSCLE = "MUSCLE"
let AFZEYESH_VAZN_HAJM = "افزایش وزن و افزایش حجم عضلات"
let Weight_gain = "Gain weight and grow muscles"
let GOAL01 = "ACTIVITY_DIET_GOAL_1"
let KAHESH_CHARBI_HEFZ_HAJM = "کاهش چربی بدن (حفظ حجم عضله)"
let Reduce_fat = "Reduce body fat (maintain muscle mass)"
let GOAL02 = "ACTIVITY_DIET_GOAL_2"
let KAHESH_CHARBI_AFZAYESH_HAJM = "کاهش چربی بدن (افزایش حجم عضله)"
let Reduce_fat_increase_muscle = "Reduce body fat & grow muscle mass"
let GOAL03 = "ACTIVITY_DIET_GOAL_3"
let TASBIT_AFZEYESH_HAJM = "تثبیت وزن و افزایش حجم عضلات"
let Weight_stabilization = "Grow muscle mass & muscular endurance"
let GOAL04 = "ACTIVITY_DIET_GOAL_4"
let AFZAYESH_HAJM_ESTEGHAMAT = "افزایش حجم عضلات و استقامت عضلانی"
let Increase_muscle_mass = "Increase muscle mass & strength"
let GOAL05 = "ACTIVITY_DIET_GOAL_5"
let AFZAYESH_HAJM_GHODRAT = "افزایش حجم و قدرت عضلات"
let Increase_muscle_volume = "Weight stabilization & increasing muscle"
let GOAL06 = "ACTIVITY_DIET_GOAL_6"
let HAVE_DOCTOR = "HAVE_DOCTOR"
let Have_Doctor = "I have diagnosis of a doctor"
let TASHKHIS_DOCTOR = "به تشخیص پزشک دارم"
let HAVE_OWN = "HAVE_OWN"
let have_osteoarthritis = "I think I have an osteoarthritis"
let FEKR_DARAM = "خودم فکر می کنم دارم"
let PLAVIX = "PLAVIX"
let Plavix = "Plavix"
let PLAVIXF = "پلاویکس"
let CLOPIDOGREL = "CLOPIDOGREL"
let Clopidogrel = "Clopidogrel"
let CLOPIDOGRELF = "کلوپیدوگرل"
let ASPIRIN = "ASPIRIN"
let Aspirin = "Aspirin"
let ASPIRINF = "آسپرین"
let ASVYKS = "ASVYKS"
let Asvyks = "Asvyks"
let ASVYKSF = "اسویکس"
let HEPARIN = "HEPARIN"
let Heparin = "Heparin"
let HEPARINF = "هپارین"
let SLKSAN = "SLKSAN"
let Slksan = "Slksan"
let SLKSANF = "سلکسان"
let WARFARIN = "وارفارین"
let Warfarin = "Warfarin"
let Not_Use = "I do not use"
let ESTEFADE_NEMIKONAM = "استفاده نمیکنم"
let JYES_BEFORE = "JYES_BEFORE"
let MIGRANE = "MIGRANE"
let Migrane = "Migrane"
let MIGREN = "میگرن"
let Up = "Up"
let BALA = "بالا"
let Down = "Down"
let PAEIN = "پایین"
let BORDER = "BORDER"
let Border_100_115 = "Border (100 to 115)"
let LAB_MARZ_100_115 = "لب مرز (۱۰۰ تا ۱۱۵)"
let HEALTHY = "HEALTHY"
let SALEM = "سالم"
let HAS_STONE = "HAS_STONE"
let Has_Stone = "Has Stone"
let SANG_DARAD = "سنگ دارد"
let NO_GALLBLADDER_BY_OPERATION = "NO_GALLBLADDER_BY_OPERATION"
let removed_surgery = "I've removed by surgery"
let KISE_SAFRA_BARDASHT = "کیسه صفرا را برداشته ام"
let Normal_Healthy = "Normal and Healthy"
let THALASSEMIA = "THALASSEMIA"
let Thalassemia = "Thalassemia Minor"
let TALASEMI = "تالاسمی مینور"
let NO_PROBLEM = "NO_PROBLEM"
let No_problem = "No problem"
let ASLAN = "اصلاً"
let SOMETIMES_PROBLEM = "SOMETIMES_PROBLEM"
let Sometimes = "Sometimes"
let GAHI = "گاهی"
let OFTEN_PROBLEM = "OFTEN_PROBLEM"
let More_often = "More often"
let BISHTAR_OGHAT = "بیشتر اوقات"
let Border_195_205 = "Border (195 to 205)"
let LAB_MARZ_195_205 = "لب مرز (۱۹۵ تا ۲۰۵)"
let Border_195_230 = "Border (195 to 230)"
let LAB_MARZ_195_230 = "لب مرز (۱۹۵ تا ۲۳۰)"
let LOW_WORK = "LOW_WORK"
let Low_work = "Low work"
let KAMKAR = "کم کار"
let LABORIOUS = "LABORIOUS"
let Labor_intensive = "Labor intensive"
let PORKAR = "پُر کار"
let Border_6_7 = "Border (6.5 to 7.1)"
let LAB_MARZ_6_7 = "لب مرز (۶۰۵ تا ۷.۱)"
let BREAKS = "BREAKS"
let Breaks = "Breaks"
let MISHEKANAD = "می شکند"
let LAMINATE = "LAMINATE"
let Laminate = "Laminate"
let VARAGHE = "ورقه ورقه"
let LOW_GROWTH = "LOW_GROWTH"
let Low_Growth = "Low Growth"
let ROSHD_KAM = "رشد کم"
let Healthy = "Healthy"
let EAT_AT_HOME = "EAT_AT_HOME"
let Eat_home_food = "Eat home food"
let GHAZA_MANZEL = "غذای منزل را میخورم"
let EAT_AT_WORK = "EAT_AT_WORK"
let Eat_work_food = "Eat work restaurant food"
let GHAZA_KAR = "غذای رستوران محل کارم را میخورم"
let EAT_AT_RESTAURANT = "EAT_AT_RESTAURANT"
let Eat_restaurant_food = "Eat restaurant food"
let GHAZA_RESTURAN = "غذای بیرون (رستوران) میخورم"
let DONE_100 = "DONE_100"
let Done_100 = "I've done 100%"
let SAD_DAR_SAD = "صد در صد انجام داده ام"
let DONE_50 = "DONE_50"
let Done_50 = "I've done more or less"
let KAM_BISH = "کم و بیش انجام داده ام"
let DONE_0 = "DONE_0"
let Done_0 = "I've not done"
let ANJAM_NADADAM = "انجام نداده ام"
let OBSERVE_100 = "OBSERVE_100"
let Observe_100 = "I've observe 100%"
let SAD_DAR_SAD_RAAYAT = "صد در صد رعایت کرده ام"
let OBSERVE_50 = "OBSERVE_50"
let Observe_50 = "I've observe more or less"
let KAM_BISH_RAAYAT = "کم و بیش رعایت کرده ام"
let OBSERVE_0 = "OBSERVE_0"
let Observe_0 = "I've not observe"
let RAAYAT_NAKARDAM = "رعایت نکرده ام"
let WEIGHT_LOSS = "WEIGHT_LOSS"
let lose_weight = "I want to lose weight"
let VAZN_KAM = "میخواهم وزنم کمتر شود"
let WEIGHT_GAIN = "WEIGHT_GAIN"
let weigh_more = "I want to weigh more"
let VAZN_BISHTAR = "میخواهم وزنم بیشتر شود"
let WEIGHT_CONSTANT = "WEIGHT_CONSTANT"
let Dont_change = "I don't want to change my weight"
let TAGHIR_NAKONAD = "میخواهم وزنم تغییری نکند"
let No_has = "No one has"
let NADARAD = "ندارد"
let DARAD = "دارد"
let HAS_IT = "Has it"

//        setBodyViewV2(from: "")
//        UIFont.familyNames.forEach({ familyName in
//            print(UIFont.fontNames(forFamilyName: familyName))
//        })
